"""initial_schema_with_graph_provenance

Revision ID: 7262e2595e75
Revises: 
Create Date: 2026-10-01 19:52:42.041310

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7262e2595e75'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_kind', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.String(length=512), nullable=False),
    sa.Column('investigation_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index('ix_investigations_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_investigations_status', ['status'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index('ix_entities_inv_id', ['investigation_id', 'id'], unique=False)
        batch_op.create_index('ix_entities_inv_kind_val', ['investigation_id', 'kind', 'value'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('predicate', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index('ix_relationships_inv_entities', ['investigation_id', 'source_entity_id', 'target_entity_id'], unique=False)
        batch_op.create_index('ix_relationships_source', ['source_entity_id'], unique=False)
        batch_op.create_index('ix_relationships_target', ['target_entity_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('relationship_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_observation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('info_classification', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_entity_id', ['entity_id'], unique=False)
        batch_op.create_index('ix_evidence_inv_entity', ['investigation_id', 'entity_id'], unique=False)
        batch_op.create_index('ix_evidence_inv_rel', ['investigation_id', 'relationship_id'], unique=False)
        batch_op.create_index('ix_evidence_inv_tool', ['investigation_id', 'tool'], unique=False)
        batch_op.create_index('ix_evidence_relationship_id', ['relationship_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_relationship_id')
        batch_op.drop_index('ix_evidence_inv_tool')
        batch_op.drop_index('ix_evidence_inv_rel')
        batch_op.drop_index('ix_evidence_inv_entity')
        batch_op.drop_index('ix_evidence_entity_id')

    op.drop_table('evidence')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index('ix_relationships_target')
        batch_op.drop_index('ix_relationships_source')
        batch_op.drop_index('ix_relationships_inv_entities')

    op.drop_table('relationships')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_inv_kind_val')
        batch_op.drop_index('ix_entities_inv_id')

    op.drop_table('entities')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index('ix_investigations_status')
        batch_op.drop_index('ix_investigations_created_at')

    op.drop_table('investigations')
    # ### end Alembic commands ###
